# Generated by Django 4.0.2 on 2023-01-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0003_alter_depositrequestconfirmation_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequestconfirmation',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
