# Generated by Django 4.0.2 on 2023-01-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_referral_direct_refer_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='invested',
            field=models.BooleanField(default=False),
        ),
    ]
