# Generated by Django 4.0.2 on 2023-01-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_referral_today_sell_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Balance'),
        ),
    ]
