# Generated by Django 4.0.2 on 2023-01-30 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0007_alter_referral_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReferral',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('reg_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Reg number')),
                ('inner_id', models.CharField(blank=True, db_index=True, editable=False, max_length=50, null=True, verbose_name='Inner ID')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Balance')),
                ('roi_profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('total_roi_profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('level_income', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('total_level_income', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('direct_refer_income', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('total_direct_refer_income', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('meek_profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('rank_profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('today_sell_volume', models.DecimalField(blank=True, decimal_places=2, default=0.01, max_digits=15, null=True)),
                ('total_sell_volume', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('trading_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('code', models.CharField(blank=True, max_length=12)),
                ('account_address', models.CharField(blank=True, max_length=60, null=True)),
                ('active', models.BooleanField(default=True)),
                ('invested', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='account')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mainapp.referral', verbose_name='Up Line')),
            ],
            options={
                'verbose_name': 'historical Referral',
                'verbose_name_plural': 'historical Referral',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
