# Generated by Django 4.0.2 on 2023-01-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_historicalreferral'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalReferral',
        ),
    ]
