# Generated by Django 4.0.2 on 2023-01-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='network_selected',
            field=models.CharField(blank=True, choices=[('BTC Bitcoin', 'BTC Bitcoin'), ('Ethereum (ERC20)', 'Ethereum (ERC20)'), ('LTC Litecoin', 'LTC Litecoin'), ('Tron (TRC20)', 'Tron (TRC20)'), ('BNB Smart Chain (BEP20)', 'BNB Smart Chain (BEP20)'), ('Cardano ', 'Cardano '), ('Polygon ', 'Polygon '), ('SOL Solana', 'SOL Solana'), ('DOGE Dogecoin', 'DOGE Dogecoin')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='coin_selected',
            field=models.CharField(blank=True, choices=[('1', 'Bitcoin'), ('2', 'USDT'), ('3', 'Ethereum'), ('3', 'BUSD'), ('4', 'Dogecoin'), ('5', 'BNB'), ('6', 'Litecoin'), ('7', 'USDC'), ('8', 'SOL Solana'), ('9', 'BNB'), ('10', 'MATIC Polygon'), ('11', 'XRP Ripple'), ('12', 'ADA Cardano')], max_length=25, null=True),
        ),
    ]
